#!/bin/bash
#Kasutaja lisamine failinimest kasutades lisa_kasutaja skripti

if [ $# -ne 1 ];

 then

    echo "Kasutusjuhend: $0 failinimi"	

else

	failinimi=$1

  if [ -f $failinimi -a -r $failinimi ]; then

    echo "fail on korras"

    for nimi in $(cat $failinimi)

    do

      #Sellega peaks faili sisu olema nähtav, kui fail on kätte saadav ja nüüd echo asemel tuleb kutsuda vajalik skript

      #echo $rida

      sh lisa_kasutaja $nimi #Sellega käivitame lisa_kasutaja skripti

    done

  else

    echo "probleem failiga $failinimi"

  fi

#Parameetrite kontrolli lõpp

fi

